export default {
  columns: [
    '订购服务',
    '单价(元)',
    '数量',
    '实付款(元)',
    '套餐有效时间',
    '剩余服务期限',
    '抵扣小计(元)',
  ],
  columns1: [
    '订购服务',
    '单价(元)',
    '数量',
    '服务期限',
    '付款小计(元)'
  ],
  menuList: [
    {
      id: 1,
      name: '免费版',
      authType: 0,
      startTime: '2018-9-20',
      endTime: '2028-9-20',
      validDay: 7,
      price: 6800 * 100,
      discountsPrice: 7800 * 100,
      usedNum: 0,
      mostBuyNum: 10,
      leave: 0,
      group: 1,
      openSell: true,
      summary: '免费体验',
      recommend: false,
      createTime: '2018-9-20',
      corpPackageId: 11,
      corpPackIdStartTime: '2018-9-20',
      corpPackIdEndTime: '2028-9-20',
      corpPackIdCreateTime: '2018-9-20',
      corpPackIdGroup: 11,
      corpPackIdLeave: 0,
      freePackageSelect: false,
    },
    {
      id: 2,
      name: '标准版',
      authType: 0,
      startTime: '2018-9-20',
      endTime: '2028-9-20',
      validDay: 15,
      price: 8800 * 100,
      discountsPrice: 9800 * 100,
      usedNum: 3,
      mostBuyNum: 10,
      leave: 1,
      group: 2,
      openSell: true,
      summary: '适合5万个粉丝',
      recommend: false,
      createTime: '2018-9-20',
      corpPackageId: 22,
      corpPackIdStartTime: null,
      corpPackIdEndTime: null,
      corpPackIdCreateTime: null,
      corpPackIdGroup: 11,
      corpPackIdLeave: 0,
      freePackageSelect: false,
    },
    {
      id: 3,
      name: '标准版',
      authType: 0,
      startTime: '2018-9-20',
      endTime: '2028-9-20',
      validDay: 30,
      price: 10800 * 100,
      discountsPrice: 10800 * 100,
      usedNum: 3,
      mostBuyNum: 5,
      leave: 2,
      group: 22,
      openSell: true,
      summary: '适合6万个粉丝',
      recommend: true,
      createTime: '2018-9-20',
      corpPackageId: 3,
      corpPackIdStartTime: null,
      corpPackIdEndTime: null,
      corpPackIdCreateTime: null,
      corpPackIdGroup: 11,
      corpPackIdLeave: 0,
      freePackageSelect: false,
    },
    {
      id: 4,
      name: '高级版',
      authType: 0,
      startTime: '2018-9-20',
      endTime: '2028-9-20',
      validDay: 60,
      price: 9800 * 100,
      discountsPrice: 10800 * 100,
      usedNum: 3,
      mostBuyNum: 10,
      leave: 3,
      group: 3,
      openSell: true,
      summary: '适合7万个粉丝',
      recommend: false,
      createTime: '2018-9-20',
      corpPackageId: 44,
      corpPackIdStartTime: null,
      corpPackIdEndTime: null,
      corpPackIdCreateTime: null,
      corpPackIdGroup: 11,
      corpPackIdLeave: 0,
      freePackageSelect: false,
    },
    {
      id: 5,
      name: '钻石版',
      authType: 0,
      startTime: '2018-9-20',
      endTime: '2028-9-20',
      validDay: 90,
      price: 11800 * 100,
      discountsPrice: 12800 * 100,
      usedNum: 6,
      mostBuyNum: 10,
      leave: 4,
      group: 5,
      openSell: true,
      summary: '适合8万个粉丝',
      recommend: false,
      createTime: '2018-9-20',
      corpPackageId: 55,
      corpPackIdStartTime: null,
      corpPackIdEndTime: null,
      corpPackIdCreateTime: null,
      corpPackIdGroup: 11,
      corpPackIdLeave: 0,
      freePackageSelect: false,
    }
  ]
}
